---

- hosts: "{{ mchost }}"
  become: false
  gather_facts: true
 
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore

  tasks: 
    - include: Tasks/main.yml
